using System.Buffers.Binary;
using System.Globalization;
using System.Text;
using PointCloudViz.Core.Data;

namespace PointCloudViz.Core.IO;

/// <summary>
/// PLY 写出器。默认输出 <c>binary_little_endian</c>，坐标使用 double 保存世界坐标，不丢精度。
/// </summary>
public sealed class PlyWriter(bool ascii = false) : IPointCloudWriter
{
    public bool Ascii { get; } = ascii;

    public string FormatName => "PLY 点云";

    public IReadOnlyList<string> Extensions { get; } = [".ply"];

    public void Write(PointCloud cloud, Stream stream, IProgress<double>? progress = null, CancellationToken cancellationToken = default)
    {
        var reporter = new ProgressReporter(progress);
        bool hasColor = cloud.Has(PointAttributes.Color);
        bool hasIntensity = cloud.Has(PointAttributes.Intensity);
        bool hasClass = cloud.Has(PointAttributes.Classification);

        var header = new StringBuilder()
            .Append("ply\n")
            .Append(Ascii ? "format ascii 1.0\n" : "format binary_little_endian 1.0\n")
            .Append("comment Generated by PointCloudViz\n")
            .Append(CultureInfo.InvariantCulture, $"element vertex {cloud.Count}\n")
            .Append("property double x\nproperty double y\nproperty double z\n");
        if (hasColor) header.Append("property uchar red\nproperty uchar green\nproperty uchar blue\n");
        if (hasIntensity) header.Append("property float intensity\n");
        if (hasClass) header.Append("property uchar classification\n");
        header.Append("end_header\n");
        var headerBytes = Encoding.ASCII.GetBytes(header.ToString());
        stream.Write(headerBytes);

        var points = cloud.Points;
        if (Ascii)
        {
            using var writer = new StreamWriter(stream, new UTF8Encoding(false), 1 << 16, leaveOpen: true);
            var ci = CultureInfo.InvariantCulture;
            for (int i = 0; i < points.Length; i++)
            {
                if ((i & 0xFFFF) == 0)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    reporter.Report(i, points.Length);
                }
                ref readonly var p = ref points[i];
                var w = cloud.ToWorld(p.Position);
                writer.Write(w.X.ToString("R", ci)); writer.Write(' ');
                writer.Write(w.Y.ToString("R", ci)); writer.Write(' ');
                writer.Write(w.Z.ToString("R", ci));
                if (hasColor) writer.Write($" {p.Color.R} {p.Color.G} {p.Color.B}");
                if (hasIntensity) { writer.Write(' '); writer.Write(p.Intensity.ToString("R", ci)); }
                if (hasClass) { writer.Write(' '); writer.Write(p.Classification); }
                writer.Write('\n');
            }
        }
        else
        {
            int recordSize = 24 + (hasColor ? 3 : 0) + (hasIntensity ? 4 : 0) + (hasClass ? 1 : 0);
            const int batch = 8192;
            var buffer = new byte[recordSize * batch];
            for (int i = 0; i < points.Length;)
            {
                cancellationToken.ThrowIfCancellationRequested();
                reporter.Report(i, points.Length);
                int n = Math.Min(batch, points.Length - i);
                for (int k = 0; k < n; k++, i++)
                {
                    ref readonly var p = ref points[i];
                    var w = cloud.ToWorld(p.Position);
                    var s = buffer.AsSpan(k * recordSize, recordSize);
                    BinaryPrimitives.WriteDoubleLittleEndian(s, w.X);
                    BinaryPrimitives.WriteDoubleLittleEndian(s[8..], w.Y);
                    BinaryPrimitives.WriteDoubleLittleEndian(s[16..], w.Z);
                    int o = 24;
                    if (hasColor) { s[o++] = p.Color.R; s[o++] = p.Color.G; s[o++] = p.Color.B; }
                    if (hasIntensity) { BinaryPrimitives.WriteSingleLittleEndian(s[o..], p.Intensity); o += 4; }
                    if (hasClass) s[o] = p.Classification;
                }
                stream.Write(buffer, 0, n * recordSize);
            }
        }
        reporter.Report(1);
    }
}
